# Generated by Django 4.1.1 on 2022-10-10 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecomerce', '0002_articulo_categoriaprod_delete_articulos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articulo',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
